-- ============================================================================
-- Grant Privileges for AI Governance Setup
-- Run this first as SECURITYADMIN or schema owner
-- ============================================================================

-- Switch to SECURITYADMIN
USE ROLE SECURITYADMIN;

-- Grant schema privileges to your working role
GRANT USAGE ON DATABASE MEDICARE_POS_DB TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT USAGE ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Grant object creation privileges
GRANT CREATE TABLE ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE VIEW ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE PROCEDURE ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT CREATE TASK ON SCHEMA MEDICARE_POS_DB.GOVERNANCE TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Grant warehouse privileges (if needed)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE MEDICARE_POS_INTELLIGENCE;
GRANT OPERATE ON WAREHOUSE COMPUTE_WH TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Grant EXECUTE TASK privilege (required to resume tasks)
GRANT EXECUTE TASK ON ACCOUNT TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Verify grants
SHOW GRANTS TO ROLE MEDICARE_POS_INTELLIGENCE;

-- Switch back to working role
USE ROLE MEDICARE_POS_INTELLIGENCE;

-- Verify access
SELECT COUNT(*) AS event_count
FROM SNOWFLAKE.LOCAL.AI_OBSERVABILITY_EVENTS
LIMIT 1;

